export const data = {
  products: [
    {
      _id: "1",
      image: "/images/p1.jpg",
      name: "DIVAS’ DREAM EARRINGS",
      description:
        "DIVAS' DREAM 18 kt rose gold earrings set with brilliant-cut spinels",
      discount: false,
      price: 2000,
      rating: 4.5,
      slug: "divas-dream-earrings",
      quantity: 5,
      category: "earrings",
    },
    {
      _id: "2",
      image: "/images/p2.jpg",
      name: "GLAMOUROUS RING",
      description: "Glamourous 14 kt white gold ring with a sparkling diamond",
      discount: false,
      price: 1500,
      rating: 4.8,
      slug: "glamourous-ring",
      quantity: 2,
      category: "rings",
    },
    {
      _id: "3",
      image: "/images/p3.jpg",
      name: "ELEGANT NECKLACE",
      description: "Elegant 22 kt gold necklace with a delicate chain",
      discount: false,
      price: 1800,
      rating: 4.2,
      slug: "elegant-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "4",
      image: "/images/p4.jpg",
      name: "CLASSIC BRACELET",
      description: "Classic sterling silver bracelet with intricate detailing",
      discount: false,
      price: 1200,
      rating: 4.6,
      slug: "classic-bracelet",
      quantity: 2,
      category: "bracelets",
    },
    {
      _id: "5",
      image: "/images/p5.jpg",
      name: "SILVER HOOP EARRINGS",
      description: "Sterling silver hoop earrings perfect for everyday wear",
      discount: false,
      price: 800,
      rating: 4.3,
      slug: "silver-hoop-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "6",
      image: "/images/p6.jpg",
      name: "SAPPHIRE ENGAGEMENT RING",
      description: "Stunning sapphire engagement ring with diamond accents",
      discount: false,
      price: 3000,
      rating: 4.9,
      slug: "sapphire-engagement-ring",
      quantity: 5,
      category: "rings",
    },
    {
      _id: "7",
      image: "/images/p7.jpg",
      name: "PEARL PENDANT NECKLACE",
      description: "Pearl pendant necklace with 14 kt gold chain",
      discount: false,
      price: 1600,
      rating: 4.1,
      slug: "pearl-pendant-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "8",
      image: "/images/p8.jpg",
      name: "DIAMOND BANGLE BRACELET",
      description: "Elegant diamond bangle bracelet in 18 kt gold",
      discount: false,
      price: 2500,
      rating: 4.7,
      slug: "diamond-bangle-bracelet",
      quantity: 0,
      category: "bracelets",
    },
    {
      _id: "9",
      image: "/images/p9.jpg",
      name: "EMERALD STUD EARRINGS",
      description: "Gorgeous emerald stud earrings with 14 kt gold setting",
      discount: false,
      price: 1200,
      rating: 4.4,
      slug: "emerald-stud-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "10",
      image: "/images/p10.jpg",
      name: "ROSE GOLD WEDDING BAND",
      description: "Rose gold wedding band with a brushed finish",
      discount: false,
      price: 1000,
      rating: 4.5,
      slug: "rose-gold-wedding-band",
      quantity: 3,
      category: "rings",
    },
    {
      _id: "11",
      image: "/images/p11.jpg",
      name: "SILVER CHARM NECKLACE",
      description: "Sterling silver charm necklace with multiple pendants",
      discount: true,
      price: 800,
      rating: 4.2,
      slug: "silver-charm-necklace",
      quantity: 11,
      category: "necklaces",
    },
    {
      _id: "12",
      image: "/images/p12.jpg",
      name: "ROSE WRAP BRACELET",
      description: "Stylish rose gold wrap bracelet with metal accents",
      discount: true,
      price: 600,
      rating: 4.0,
      slug: "rose-wrap-bracelet",
      quantity: 7,
      category: "bracelets",
    },
    {
      _id: "13",
      image: "/images/p13.jpg",
      name: "GOLDEN HOOP EARRINGS",
      description: "Classic golden hoop earrings for any occasion",
      discount: true,
      price: 950,
      rating: 4.6,
      slug: "golden-hoop-earrings",
      quantity: 7,
      category: "earrings",
    },
    {
      _id: "14",
      image: "/images/p14.jpg",
      name: "DIAMOND HALO RING",
      description: "Exquisite diamond halo ring in 18 kt white gold",
      discount: false,
      price: 2800,
      rating: 4.9,
      slug: "diamond-halo-ring",
      quantity: 7,
      category: "rings",
    },
    {
      _id: "15",
      image: "/images/p15.jpg",
      name: "HEART-SHAPED LOCKET",
      description: "Heart-shaped locket necklace with space for two photos",
      discount: true,
      price: 750,
      rating: 4.3,
      slug: "heart-shaped-locket",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "16",
      image: "/images/p16.jpg",
      name: "BEADED STRETCH BRACELET",
      description: "Colorful beaded stretch bracelet for a boho look",
      discount: true,
      price: 500,
      rating: 4.1,
      slug: "beaded-stretch-bracelet",
      quantity: 0,
      category: "bracelets",
    },
    {
      _id: "17",
      image: "/images/p17.jpg",
      name: "PEARL DROP EARRINGS",
      description: "Elegant pearl drop earrings with 14 kt gold hooks",
      discount: false,
      price: 1100,
      rating: 4.4,
      slug: "pearl-drop-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "18",
      image: "/images/p18.jpg",
      name: "PLATINUM ENGAGEMENT RING",
      description: "Exquisite platinum engagement ring with a large diamond",
      discount: false,
      price: 4500,
      rating: 4.8,
      slug: "platinum-engagement-ring",
      quantity: 10,
      category: "rings",
    },

    {
      _id: "19",
      image: "/images/p19.jpg",
      name: "DAINTY INITIAL NECKLACE",
      description: "Dainty initial necklace with customizable letter pendant",
      discount: false,
      price: 850,
      rating: 4.6,
      slug: "dainty-initial-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "20",
      image: "/images/p20.jpg",
      name: "ENGRAVED CUFF BRACELET",
      description: "Elegant engraved cuff bracelet in sterling silver",
      discount: true,
      price: 700,
      rating: 4.2,
      slug: "engraved-cuff-bracelet",
      quantity: 10,
      category: "bracelets",
    },
    {
      _id: "21",
      image: "/images/p21.jpg",
      name: "DIAMOND STUD EARRINGS",
      description: "Timeless diamond stud earrings with a brilliant shine",
      discount: false,
      price: 2000,
      rating: 4.9,
      slug: "diamond-stud-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "22",
      image: "/images/p22.jpg",
      name: "VINTAGE SAPPHIRE RING",
      description: "Vintage-style sapphire ring with intricate detailing",
      discount: false,
      price: 1800,
      rating: 4.7,
      slug: "vintage-sapphire-ring",
      quantity: 0,
      category: "rings",
    },
    {
      _id: "23",
      image: "/images/p23.jpg",
      name: "GOLD CHOKER NECKLACE",
      description: "Chic gold choker necklace with a minimalist design",
      discount: false,
      price: 600,
      rating: 4.3,
      slug: "gold-choker-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "24",
      image: "/images/p24.jpg",
      name: "METAL BRACELET",
      description: "Edgy  metal bracelet for a modern look",
      discount: true,
      price: 550,
      rating: 4.0,
      slug: "metal-bracelet",
      quantity: 10,
      category: "bracelets",
    },
    {
      _id: "25",
      image: "/images/p25.jpg",
      name: "HOOP EARRINGS SET",
      description: "Set of three hoop earrings in different sizes and metals",
      discount: false,
      price: 1000,
      rating: 4.5,
      slug: "hoop-earrings-set",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "26",
      image: "/images/p26.jpg",
      name: "ROSE GOLD STACKABLE RINGS",
      description: "Stackable rose gold rings with delicate gemstone accents",
      discount: true,
      price: 850,
      rating: 4.2,
      slug: "rose-gold-stackable-rings",
      quantity: 0,
      category: "rings",
    },
    {
      _id: "27",
      image: "/images/p27.jpg",
      name: "PENDANT NECKLACE WITH TASSEL",
      description: "Stylish pendant necklace with a trendy tassel",
      discount: true,
      price: 700,
      rating: 4.6,
      slug: "pendant-necklace-with-tassel",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "28",
      image: "/images/p28.jpg",
      name: "BOHEMIAN BEADED BRACELET",
      description: "Bohemian-style beaded bracelet with vibrant colors",
      discount: true,
      price: 450,
      rating: 4.1,
      slug: "bohemian-beaded-bracelet",
      quantity: 10,
      category: "bracelets",
    },
    {
      _id: "29",
      image: "/images/p29.jpg",
      name: "DIAMOND DROP EARRINGS",
      description: "Elegant diamond drop earrings with a timeless design",
      discount: false,
      price: 1400,
      rating: 4.7,
      slug: "diamond-drop-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "30",
      image: "/images/p30.jpg",
      name: "ART DECO COCKTAIL RING",
      description: "Art Deco-inspired cocktail ring with geometric patterns",
      discount: false,
      price: 2200,
      rating: 4.8,
      slug: "art-deco-cocktail-ring",
      quantity: 10,
      category: "rings",
    },
    {
      _id: "31",
      image: "/images/p31.jpg",
      name: "GOLD LAYERED NECKLACE",
      description: "Layered gold necklace with multiple chains",
      discount: false,
      price: 800,
      rating: 4.4,
      slug: "gold-layered-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "32",
      image: "/images/p32.jpg",
      name: "ENAMEL BANGLE BRACELET",
      description: "Colorful enamel bangle bracelet for a fun accessory",
      discount: true,
      price: 650,
      rating: 4.3,
      slug: "enamel-bangle-bracelet",
      quantity: 10,
      category: "bracelets",
    },
    {
      _id: "33",
      image: "/images/p33.jpg",
      name: "GOLD TEARDROP EARRINGS",
      description: "Graceful gold teardrop earrings for an elegant look",
      discount: false,
      price: 900,
      rating: 4.5,
      slug: "gold-teardrop-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "34",
      image: "/images/p34.jpg",
      name: "HALO DIAMOND ENGAGEMENT RING",
      description: "Halo diamond engagement ring with a dazzling center stone",
      discount: false,
      price: 3500,
      rating: 4.9,
      slug: "halo-diamond-engagement-ring",
      quantity: 10,
      category: "rings",
    },
    {
      _id: "35",
      image: "/images/p35.jpg",
      name: "CROSS PENDANT NECKLACE",
      description: "Elegant cross pendant necklace in 18 kt gold",
      discount: false,
      price: 1100,
      rating: 4.3,
      slug: "cross-pendant-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "36",
      image: "/images/p36.jpg",
      name: "GOLD CHAIN BRACELET",
      description: "Classic gold chain bracelet for a timeless accessory",
      discount: true,
      price: 500,
      rating: 4.0,
      slug: "gold-chain-bracelet",
      quantity: 10,
      category: "bracelets",
    },
    {
      _id: "37",
      image: "/images/p37.jpg",
      name: "PEARL AND DIAMOND EARRINGS",
      description: "Pearl and diamond earrings for an elegant combination",
      discount: false,
      price: 1200,
      rating: 4.6,
      slug: "pearl-and-diamond-earrings",
      quantity: 10,
      category: "earrings",
    },
    {
      _id: "38",
      image: "/images/p38.jpg",
      name: "DIAMOND ETERNITY BAND",
      description: "Timeless diamond eternity band in platinum",
      discount: false,
      price: 2800,
      rating: 4.8,
      slug: "diamond-eternity-band",
      quantity: 10,
      category: "rings",
    },
    {
      _id: "39",
      image: "/images/p39.jpg",
      name: "ENAMEL CHARM NECKLACE",
      description: "Enamel charm necklace with delicate gold chain",
      discount: true,
      price: 700,
      rating: 4.4,
      slug: "enamel-charm-necklace",
      quantity: 10,
      category: "necklaces",
    },
    {
      _id: "40",
      image: "/images/p40.jpg",
      name: "BRAIDED SILVER BRACELET",
      description: "Braided silver bracelet with stainless steel clasp",
      discount: true,
      price: 550,
      rating: 4.1,
      slug: "braided-silver-bracelet",
      quantity: 10,
      category: "bracelets",
    },
  ],
};
